### ISSUE TITLE
Macro Record/Playback (vim-style)

### ISSUE THREAD

**Issue by haata** [kiibohd/controller#279]
It would be nice to have a record/playback mechanism for macros, similar to what's available in vim.
For details on how vim records macros see: http://vim.wikia.com/wiki/Recording_keys_for_repeated_jobs

This feature does not require KLL support to integrate as it should be sufficient to use generic capabilities to achieve macro record/playback.

## Proposed Outline

- Add two capabilities that takes a single argument
  - Record macro
  - Replay macro
- Argument indicates which macro is being replayed back
- Each macro has a maximum internal memory allocated to it
- Allocate a bulk storage
  - Add macros to the heap, compacting them together when a macro is replaced
  - If memory is full, don't record the macro and indicate some kind of error.
  - Amount of memory allocated defined in KLL in terms of the number of input trigger elements

### KLL Definition

```bash
# Defines size of record macro buffer in number of trigger elements
RecordMacroBufferSize =>RecordMacroBufferSize_define;
RecordMacroBufferSize =  25; # Arbitrary value, should be tuned for the user

U"Ctrl" + U"A" : recordMacro(0);
U"A" : playMacro(0);
U"Ctrl" + U"B" : recordMacro(1);
U"B" : playMacro(1);
```

### Record Macro

In terms of C implementation, when a `recordMacro()` capability is called PartialMap should be put into **record mode** where each of the input triggers from the macroTriggerEventBuffer are recorded per cycle to determine what goes into the RecordMacro buffer.

Any input triggers in the same cycle are considered a combination, and input triggers in a different cycle are considered a sequence.
Compact "dead time" into a single input trigger (either null or the current pressed combination/single key).

Here is a good approximate place to implement the record feature: https://github.com/kiibohd/controller/blob/7764db6e014e14f4d591afde0e60bf4f291347fa/Macro/PartialMap/macro.c#L814 as all input triggers will be added to macroTriggerEventBuffer then (which is why the debug code is there).

### Play Macro

For the replay, there are two things that need to happen.

- The capability was triggered, queue up the macro
- Add the macro elements to macroTriggerEventBuffer

This distinction has to be made as the macro processing occurs in a periodic execution thread that must not be run asynchronously (modifying macroTriggerEventBuffer is not thread-safe and must affect the *next* macro processing cycle).
Double-check to make sure macroTriggerEventBuffer is safe to modify when capabilities are being called (not sure when it is cleared for the next cycle).
Do not use a thread-unsafe capability here as it will have unexpected behavior.

## TODO

- [ ] Spec out implementation
- [ ] Write test plan
- [ ] Implement feature
- [ ] Add unit test
- [ ] Merge to master
